### ISSUE TITLE
TypeError: PythonShell is not a constructor

### ISSUE THREAD

**Issue by metalshreds** [Txukie/MMM-LCDControl#2]
tried using the module and get the following error, any idea how I can resolve it? thanks!
```
TypeError: PythonShell is not a constructor
    at Class.python_start (/home/pi/MagicMirror/modules/MMM-LCDControl/node_helper.js:12:21)
    at Class.socketNotificationReceived (/home/pi/MagicMirror/modules/MMM-LCDControl/node_helper.js:76:14)
    at Socket.<anonymous> (/home/pi/MagicMirror/modules/node_modules/node_helper/index.js:113:11)
    at Socket.emit (events.js:182:13)
    at /home/pi/MagicMirror/node_modules/socket.io/lib/socket.js:513:12
    at process._tickCallback (internal/process/next_tick.js:61:11)
```

**Comment by crushedy** [comment]
Just modify the node_helper.js line 3:
const {PythonShell} = require('python-shell');
